### ISSUE TITLE
signatory包的版本

### ISSUE THREAD

**Issue by leirongzhen** [HBhswl/AEC-GAN#1]
非常感谢您能开源这个代码，我在复现过程中，在安装signatory包之后，一直报错，就像这样：importError: DLL load failed: 找不到指定的程序。希望作者能将您使用的版本号公布一下，还有针对我这个问题，您有什莫好的建议，期待您的回复。

**Comment by HBhswl** [comment]
本项目使用的signatory版本为1.2.6，另外关于 importError 的问题，可能是因为signatory跟pytorch的版本不适配的原因，可以参考这个isssue: https://github.com/patrick-kidger/signatory/issues/37, 从而来调整 pytorch 或者 signatory的版本

**Comment by leirongzhen** [comment]
谢谢您的回复，我试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月6日(周四) 晚上8:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HBhswl/AEC-GAN] signatory包的版本 (Issue #1)




 
本项目使用的signatory版本为1.2.6，另外关于 importError 的问题，可能是因为signatory跟pytorch的版本不适配的原因，可以参考这个isssue: patrick-kidger/signatory#37, 从而来调整 pytorch 或者 signatory的版本

**Comment by leirongzhen** [comment]
抱歉给您回复的比较晚，我按照您的说法，重新创建了一个环境，安装就没问题了，我在用数据集ILI的过程中，发现在algos文件夹中并没用AEC-GAN的python文件，您能提供一下吗?

**Comment by HBhswl** [comment]
你好，AECGAN实现于lib.algos.asganadv路径下

**Comment by leirongzhen** [comment]
嗯嗯，看到了，之前加了双引号，一直报错。谢谢

**Comment by Apple-PPon** [comment]
我的torch版本是1.8.1，signatory版本是1.2.6.1.7，为什么也是报错

**Comment by Apple-PPon** [comment]
windows64系统，python版本是3.6.7rc1

**Comment by Apple-PPon** [comment]
作者能否提供下依赖包的版本啊（sklearn，numpy这些）

**Comment by Apple-PPon** [comment]
总是报同一个错误：ImportError: DLL load failed while importing _impl: 找不到指定的程序。
看上去是signatory的库出问题了。好几个方法都不行。试过重装升级也不行。
我试过用3.6，3.8的python安装对应的torch库，或者是用最新的torch（signatory用1.2.6附近的版本跟torch排列组合），都报这个错。
然后我用3.10的python试了下，torch是最新的2.3.1+cu118，signatory也是最新的，这次就明面上能跑，但是报错：RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
这个问题我用gpt解决了，然后我发现原文件里面作者把这个代码给注释了。
在train.py的114行，改成”x_real = x_real.to(base_config.device)“
